version: "3.9"
services:
  app:
    build: .
    container_name: rtc_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+aiomysql://brajesh350194:Beast@5uuu@mysql:3306/rt_collab"
      REDIS_URL: "redis://redis:6379/0"
      ALLOWED_ORIGINS: "http://localhost:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["uvicorn", "rt_collab.main:app", "--host", "0.0.0.0", "--port", "8000"]

  mysql:
    image: mysql:8.0
    container_name: rtc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rt_collab
      MYSQL_USER: "brajesh350194"
      MYSQL_PASSWORD: "Beast@5uuu"
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: rtc_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysqldata:
    driver: local
