version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: rtc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rt_collab
      MYSQL_USER: "brajesh350194"
      MYSQL_PASSWORD: "Beast@5uuu"
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: rtc_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  mysqldata:
    driver: local
